Init skeleton pages
ianleck/is4103-frontend pull request #1
Opened 2021-02-13 19:48 UTC by rawrrencee

### Changelog: 
Added components in their respective folders (Admin/Sensei/Student/Public)
Added layouts for Admin/Student/Sensei
Included dynamic menu changes in Admin/Student/Sensei layouts (MenuTop/MenuLeft custom components)
Modified existing Main layout for non-logged-in usage
Added admin, sensei, student skeleton pages (/dashboard)
Modified routers.js to include skeleton pages (navigate via url e.g. /admin/dashboard)
## Description:
This change initializes the develop branch to begin front-end development.
## Checklist:
- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):
Student Page
![image](https://user-images.githubusercontent.com/43084055/107859840-3c7e3600-6e77-11eb-9ab1-a7221ebe5fe3.png)
Sensei Page
![image](https://user-images.githubusercontent.com/43084055/107859823-28d2cf80-6e77-11eb-9b23-507a858f3e66.png)
Admin Page
![image](https://user-images.githubusercontent.com/43084055/107859854-4dc74280-6e77-11eb-83d0-719001141e85.png)

2021-02-14 03:13 UTC, natalieloke requested changes

2021-02-14 03:13 UTC, natalieloke commented on src/components/Sensei/SenseiMenuBar/UserMenu/style.module.scss
> +    @include transition-slow();
can i check if this parentheses is intended?

2021-02-14 03:13 UTC, natalieloke commented on src/components/Sensei/SenseiMenuBar/Actions/index.js
> +    <React.Fragment>
we can use the new shorter syntax for react fragment which is ```<> ... </>```
https://reactjs.org/docs/fragments.html#short-syntax

2021-02-14 03:16 UTC, natalieloke commented on src/components/Public/PublicMenuBar/MenuLeft/index.js
> +  }
these seem duplicated across several files in folders regarding a MenuBar. can we consider moving them to a relevant utils file where we export it and then import it to use them?

2021-02-14 09:08 UTC, y1bs commented
I agree with Nat's Point

On the admin side, every else looks good! Thanks Lawrence!

2021-02-14 17:47 UTC, rawrrencee commented on src/components/Public/PublicMenuBar/MenuLeft/index.js
> +  }
Somehow did not manage to export the consts used due to my limited knowledge, I don't really know how to export it so that the variables its calling are still accessible
I think need your help to try this out, @natalieloke 
Would be good to have a sample of how you would do it, as I'm still new to React, this part is quite hard for me haha

2021-02-14 17:50 UTC, rawrrencee commented on src/components/Sensei/SenseiMenuBar/Actions/index.js
> +    <React.Fragment>
Done!

2021-02-14 17:51 UTC, rawrrencee commented on src/components/Sensei/SenseiMenuBar/UserMenu/style.module.scss
> +    @include transition-slow();
Yep, intended, I switched the menu this SenseiMenuBar was referencing from!

2021-02-15 12:51 UTC, natalieloke commented on src/components/Public/PublicMenuBar/MenuLeft/index.js
> +  }
ok will do! 👍

2021-02-15 12:52 UTC, natalieloke approved these changes

2021-02-15 13:08 UTC, merged