mentorship tasks
ianleck/is4103-frontend pull request #103
Opened 2021-04-02 11:20 UTC by kengthong

# Feature

Use Case: D.1.10 View Mentorship Tasks
Feature ID : _Eg; 1_
Feature: _Eg; Sensei/Student Account Access_
Figma link for wireframe:

# Changelog:

# Merge/Review Order

These other PRs should be merged or reviewed first

This PR blocks these other PRs

## Checklist:

- [ ] Merged latest develop
- [ ] PR title makes sense

## Screenshots (where relevant):

2021-04-02 18:10 UTC, rawrrencee submitted a review, later dismissed
@natalieloke for your review~ I think code is ok! but need your help to test the business logic part of this to see if any changes will b required. thanks!

2021-04-03 01:55 UTC, natalieloke requested changes
Thanks KT 🙏🏼 Left some comments! Biz logic wise I think it seems ok from the code, a video would help! Else we can always build up on the biz logic on subsequent PRs :) 

cc @rawrrencee

2021-04-03 01:55 UTC, natalieloke commented on src/components/Mentorship/Subscription/TaskBucket.js
> +              title="Do you wish to delete admin account?"
Need to change pasta-ed text

2021-04-03 01:55 UTC, natalieloke commented on src/components/Mentorship/ListingDetails/MentorshipProfileHeader.js
> +      ) : null}
If the false condition returns null will it just be easier to put` !isSubscription && <Button....>`

Also helps w readability!

2021-04-03 01:55 UTC, natalieloke commented on src/components/Mentorship/Subscription/TaskBucket.js
> +      {taskBuckets.map((tb, i) => {
Can we use lodash's map? JavaScript map has some issues when the object is empty/null/undefined (I forgot which lol)

2021-04-03 01:55 UTC, natalieloke commented on src/components/Mentorship/Subscription/TaskRow.js
> +              <Tag
U can check out StatusTag component which show diff colours!

2021-04-03 14:22 UTC, natalieloke approved these changes

2021-04-03 14:29 UTC, rawrrencee commented on src/components/Mentorship/ListingDetails/MentorshipProfileHeader.js
>      <div className="row justify-content-between ">
extra space, if wanna modify can, if not its ok too

2021-04-03 14:29 UTC, rawrrencee commented on src/components/Mentorship/Subscription/TaskRow.js
> +        <div className="col-12 col-md-4 d-flex ">
extra space here too, not necessary to fix

2021-04-03 14:30 UTC, rawrrencee approved these changes
looks good to me! there's some small stuff like equivalent classNames for some style={{ }} stuff, but since its equivalent, i think can leave it. there's also some div classNames="... " extra spacing behind the ..., I have left comments on them. but don't change also nvm~

2021-04-03 14:33 UTC, merged

2021-04-03 14:33 UTC, natalieloke commented
> looks good to me! there's some small stuff like equivalent classNames for some style={{ }} stuff, but since its equivalent, i think can leave it. there's also some div classNames="... " extra spacing behind the ..., I have left comments on them. but don't change also nvm~

ok i'll change those along the way in subsequent PRs thanks! @rawrrencee