A.1.3 Create a User Account (Student)
ianleck/is4103-frontend pull request #14
Opened 2021-02-19 06:45 UTC by rawrrencee

# Feature

Use Case: Create a User Account (Student)
Feature ID: 1
Feature: Sensei/Student Account Access
Figma link for wireframe:N.A.

# Changelog:
Update SVG of Digi Dogo logo to be dark navy blue
Added redux action for triggering a second profile update form once account has been created.
TODO: 
implement form validation logic
implement backend API integration (currently still basing it off mock API)

# Merge/Review Order
This PR should be squashed and merged as a single commit due to overlapping commits. This branch was based off another branch initially (and not develop) hence the other branch's commits were listed as new ones in this commit log.

## Checklist:

- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/43084055/108467940-f256e380-72c0-11eb-921f-591762a4ff6f.png">
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/43084055/108467964-fc78e200-72c0-11eb-96b2-dfd7a3fac923.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/43084055/108467980-039ff000-72c1-11eb-83f3-7157dbb30f9d.png">

2021-02-19 09:56 UTC, natalieloke requested changes

2021-02-19 09:56 UTC, natalieloke commented on src/components/cleanui/system/Auth/Register/index.js
> +const Register = ({ user, dispatch }) => {
`Register` is a functional component (FC). We can use hooks that React has designed for FCs. 
mapStateToProps is originally designed for class components, but it won't break FCs. the FCs equivalent is [useSelector](https://react-redux.js.org/api/hooks#useselector). and to get [dispatch](https://react-redux.js.org/api/hooks#usedispatch) we can do `const dispatch = useDispatch()`

2021-02-19 09:56 UTC, natalieloke commented on src/components/cleanui/system/Auth/Register/index.js
> +  const onFinishUpdateProfile = values => {
what's the rationale for the `onFinish` prefix here for several variables? i think it's not really necessary

2021-02-19 09:56 UTC, natalieloke commented on src/redux/user/sagas.js
> +    }
eventually for updating profile of admin and sensei we will change the if condition?

2021-02-19 09:56 UTC, natalieloke commented on src/redux/user/sagas.js
> +      },
`loading: false` here?

2021-02-19 09:56 UTC, natalieloke commented on src/redux/user/sagas.js
> +    },
this should only be set when update profile is done?

2021-02-19 09:56 UTC, natalieloke commented on src/redux/user/sagas.js
> +      },
cos success alr

2021-02-19 09:56 UTC, natalieloke commented on src/redux/user/sagas.js
> +      },
since loading is false has to be set after ` mapAuthProviders[autProviderName].updateProfile`, we can put this entire chunk out of the else block

2021-02-19 09:56 UTC, natalieloke commented on src/components/cleanui/system/Auth/Register/index.js
> +  return signUpCard
this FC isn't purely register. it is either update profile or register profile. the naming 'Register' can be a bit misleading

2021-02-19 17:00 UTC, rawrrencee commented on src/components/cleanui/system/Auth/Register/index.js
> +const Register = ({ user, dispatch }) => {
noted, this was the original Register page's stuff, didn't know, will try to change and commit the altered version if it works.

2021-02-19 17:01 UTC, rawrrencee commented on src/components/cleanui/system/Auth/Register/index.js
> +  const onFinishUpdateProfile = values => {
the naming of the element? oh the example I copied this from already had 'onFinish' in the naming, so I just added on to it. will change.

2021-02-19 17:02 UTC, rawrrencee commented on src/redux/user/sagas.js
> +    }
yup, add on to the if conditions

2021-02-19 17:08 UTC, rawrrencee commented on src/redux/user/sagas.js
> +      },
ok

2021-02-19 17:12 UTC, rawrrencee commented on src/redux/user/sagas.js
> +      },
ok

2021-02-19 17:15 UTC, rawrrencee commented on src/components/cleanui/system/Auth/Register/index.js
> +  return signUpCard
actually there's no "register profile". it is doing "create a user account" + "update profile".

but will name it more specific. maybe StudentRegistration? the registration flow makes it mandatory for users to update their profile immediately after creating their account, so i'm not sure how 'Register' is misleading.

2021-02-19 17:18 UTC, rawrrencee commented on src/components/cleanui/system/Auth/Register/index.js
> +const Register = ({ user, dispatch }) => {
ok it works!

2021-02-19 17:23 UTC, rawrrencee commented on src/redux/user/sagas.js
> +    },
i think it is not, it determines whether the button is showing a loading indicator right? TRIGGER_UPDATE_PROFILE makes the page show the 2nd step of the form, so once we call the action to transfer the page to the 2nd step, we can just end the loading indicator of the button

![image](https://user-images.githubusercontent.com/43084055/108538673-0549d200-731a-11eb-9dd4-c22946138c9c.png)

2021-02-19 17:28 UTC, rawrrencee commented on src/components/cleanui/system/Auth/Register/index.js
> +  return signUpCard
I take it back, will leave it as Register. unless you have a much better suggestion. it seems like it is purely register to me, because no other page will use this component.
Sensei has a different registration page while this uses the default auth/register.

2021-02-21 06:30 UTC, natalieloke approved these changes

2021-02-21 06:30 UTC, natalieloke commented on src/services/firebase/index.js
> +}
actually if we aren't using firebase do we still have to add an update profile function for it

2021-02-21 06:30 UTC, natalieloke commented on src/components/cleanui/system/Auth/Register/index.js
> +  return signUpCard
ok gotcha

2021-02-21 06:31 UTC, natalieloke commented on src/components/cleanui/system/Auth/Register/index.js
> +const Register = ({ user, dispatch }) => {
nice ok

2021-02-21 06:31 UTC, natalieloke commented on src/redux/user/sagas.js
> +    },
ok

2021-02-21 07:11 UTC, rawrrencee commented on src/services/firebase/index.js
> +}
no need, but I'll remove all one shot when doing the backend integration :)

2021-02-21 07:17 UTC, merged