Integrate Backend Endpoints
ianleck/is4103-frontend pull request #17
Opened 2021-02-25 09:00 UTC by rawrrencee

# Changelog:
Integrated the following endpoints:
Student: Login, Register, Logout (localStorage only, no API), Update Profile
Sensei: Login (same as student endpoint)
Admin: Login (same as student endpoint)

Introduced routing changes which fixes issues such as redirecting to "/" or "/sensei" when re-compiling.

Blocking of irrelevant routes ("/admin" for non-admins etc.) should work correctly now.

Profile card changes to include disclaimer for incomplete profile based on condition user.requiresProfileUpdate attribute (subject to changes)

## Checklist:

- [x] Merged latest develop
- [x] PR title makes sense

2021-02-25 09:20 UTC, y1bs submitted a review, later dismissed
Looks good to me

2021-02-25 11:05 UTC, natalieloke requested changes

2021-02-25 11:05 UTC, natalieloke commented on src/layouts/index.js
> +        return <Redirect to="/auth/login" />
this is a subset of lines 66 and 67?

2021-02-25 11:05 UTC, natalieloke commented on src/layouts/index.js
> +        return null
this condition will never be fulfilled cos it's inside the if block where `isUserAuthorised` is not falsey
```suggestion
      if (isUserAuthorized) { ... } 
      
      // at this point isUserAuthorized is falsey
      if (isUserLoading && !isAuthLayout) {
        // show loader when user in check authorization process, not authorized yet and not on login pages
        return null
```

2021-02-25 11:05 UTC, natalieloke commented on src/pages/auth/register-sensei/index.js
> +        return <Redirect to="/" />
why do we have non-sensei redirection inside `RegisterSensei`?

2021-02-25 11:05 UTC, natalieloke commented on src/pages/student/profile/index.js
> +      {user.requiresProfileUpdate && <UpdateProfileNotice />}
for all relevant boolean conditions i suggest using the double exclamation mark (!!)

this converts falsey values to false, and truthy values to true

more info: https://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript

```suggestion
      {!!user.requiresProfileUpdate && <UpdateProfileNotice />}
```

2021-02-25 11:05 UTC, natalieloke commented on src/redux/selectors.js
> +}
this is essentially dispatching an action to reset the respective reducer to the initial state? in this implementation the store (as the single source of truth) is bypassed

2021-02-25 11:05 UTC, natalieloke commented on src/redux/selectors.js
> +}
this is the selector file.

> a selector is a function that knows how to extract a specific piece of data from the store.
see more: https://stackoverflow.com/questions/38674200/what-are-selectors-in-redux

i suggest putting these functions inside a separate util file for a cleaner separation of concerns

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
>      })
need to check for user object also. 
```
const {accessToken, user} = response.data
if (!!user) {
  if (!!accessToken){
     //setLocalAccessToken and setLocalUserData
  }
 return user
}
```

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
>      })
see above comment

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
>      .then(response => {
what happens if no `accountId` is passed in?

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
> +      if (response) return response.data.user
what happens if `response.data` is undefined? or if `response.data.user` is undefined?

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
>      })
to be safe i would suggest doing a check for the params before calling the api

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
> +        return response.data.sensei
similar to above what if `response.data` is undefined and if `response.data.student` or `response.data.sensei` is undefined

2021-02-25 11:05 UTC, natalieloke commented on src/redux/selectors.js
> +    loading: isResponse ? false : currentAdmin.loading,
i am confused by this assignment. so if isResponse is false, but currentAdmin.authorised === true, authorised is still true. 

why not just do `authorised: currentAdmin.authorized`? 

i have a similar comment for `loading` here and also for `authorised`, `loading`, `requiresProfileUpdate` for `createStudentObject` above

2021-02-25 11:05 UTC, natalieloke commented on src/services/axios/index.js
> +    const accessToken = localStorage.getItem('accessToken')
what about the case where localStorage.getItem('accessToken') is undefined?

can use lodash's `isNil` here 

also localStorage.getItem('accessToken') is duplicated

```
const accessToken = localStorage.getItem('accessToken')
if(!isNil(accessToken){
 request.headers.Authorization = `Bearer ${accessToken}`
}
```

2021-02-25 11:05 UTC, natalieloke commented on src/services/axios/index.js
> +      message: data.error.message,
what if `data.error` is undefined and likewise for `data.error.message`?

2021-02-25 11:05 UTC, natalieloke commented on src/services/jwt/index.js
> +    : JSON.parse(localStorage.getItem('user'))
duplicated localStorage.getItem('user')

for a better catch we can use `isNil` as well

2021-02-25 12:28 UTC, rawrrencee commented on src/redux/selectors.js
> +}
ok!

2021-02-25 12:30 UTC, rawrrencee commented on src/services/axios/index.js
> +      message: data.error.message,
ok I try to check because if front end handle the validation properly, backend should always send bsck a populated data.error.message

2021-02-25 12:31 UTC, rawrrencee commented on src/services/jwt/index.js
> +    : JSON.parse(localStorage.getItem('user'))
ok!

2021-02-25 12:31 UTC, rawrrencee commented on src/services/jwt/index.js
>      .then(response => {
this api not ready hahaha just put in halfway. but will fix for this PR

2021-02-25 12:33 UTC, rawrrencee commented on src/layouts/index.js
> +        return <Redirect to="/auth/login" />
not sure, this is only checked when ifUserAuthorized is false I think? while 66/67 is when ifUserAuthorized is true

2021-02-25 12:37 UTC, rawrrencee commented on src/redux/selectors.js
> +}
need to check. may be able to remove this. at first this is used to 'unset' the localStorage and redux storage when logging out (instead of removing the object)

2021-02-25 13:09 UTC, natalieloke commented on src/layouts/index.js
> +        return <Redirect to="/auth/login" />
you are right, i saw the if condition block wrongly

2021-02-25 13:12 UTC, natalieloke commented on src/layouts/index.js
> +        (/^\/admin(?=\/|$)/i.test(pathname) && user.userType !== USER_TYPE_ENUM.ADMIN) ||
actually for this admin case it would be to `return <Redirect to="/auth/admin" />` right @rawrrencee

2021-02-25 18:15 UTC, rawrrencee commented on src/pages/auth/register-sensei/index.js
> +        return <Redirect to="/" />
need to block all accesses to /auth/register && /auth/register-sensei links when the user is authorized.
made this clearer by merging Register for Sensei and Student into the same element but on different pages.

2021-02-25 18:24 UTC, rawrrencee commented on src/layouts/index.js
> +        return null
refer to teams for alternative to this, its not very ideal also, but no time le, i think need to leave it for now

2021-02-25 18:24 UTC, rawrrencee commented on src/pages/auth/register-sensei/index.js
> +        return <Redirect to="/" />
this is necessary, so leaving it!

2021-02-25 19:10 UTC, rawrrencee commented on src/layouts/index.js
> +        (/^\/admin(?=\/|$)/i.test(pathname) && user.userType !== USER_TYPE_ENUM.ADMIN) ||
/auth/login is basically the main source of Redirect, meaning, all the pages not supposed to be correct one, throw to /auth/login, then /auth/login will redirect to the right page based on userType.
Sort of a workaround, but necessary so that users cannot navigate to the wrong pages.

2021-02-25 19:26 UTC, rawrrencee commented on src/services/axios/index.js
> +    const accessToken = localStorage.getItem('accessToken')
ok

2021-02-25 19:28 UTC, rawrrencee commented on src/redux/selectors.js
> +}
ok, i removed these 2. and only keep the 3 local attributes. this is needed when localStorage has nothing to return but we need to check if user.authorized is valid

2021-02-25 19:32 UTC, rawrrencee commented on src/pages/student/profile/index.js
> +      {user.requiresProfileUpdate && <UpdateProfileNotice />}
ok!

2021-02-25 19:35 UTC, rawrrencee commented on src/services/jwt/index.js
>      })
eslint is not allowing this
![image](https://user-images.githubusercontent.com/43084055/109207049-a4237200-77e3-11eb-9338-72e1e6fd7bff.png)

2021-02-25 19:43 UTC, rawrrencee commented on src/services/jwt/index.js
>      })
issue with doing the checking is that 
successful calls return object.data.success = true
failed calls return object.success = false (without the .data object)
![image](https://user-images.githubusercontent.com/43084055/109207687-5d824780-77e4-11eb-9f14-da0ad3827772.png)
![image](https://user-images.githubusercontent.com/43084055/109207734-6bd06380-77e4-11eb-9d64-9a790d9ae8cc.png)


This is the most robust I can make it
![image](https://user-images.githubusercontent.com/43084055/109208047-ce296400-77e4-11eb-80c3-7e647f93d7c0.png)

2021-02-25 20:02 UTC, rawrrencee commented on src/services/jwt/index.js
>      })
resolved as per above method

2021-02-25 20:02 UTC, rawrrencee commented on src/services/jwt/index.js
>      .then(response => {
removed this api first since its not ready and I can't call it yet on frontend

2021-02-25 20:02 UTC, rawrrencee commented on src/services/jwt/index.js
> +      if (response) return response.data.user
removed as per above

2021-02-25 20:03 UTC, rawrrencee commented on src/services/jwt/index.js
>      })
ok, noted for future

2021-02-25 20:05 UTC, rawrrencee commented on src/services/jwt/index.js
> +        return response.data.sensei
fixed as per isNil method

2021-02-25 20:06 UTC, rawrrencee commented on src/redux/selectors.js
> +    loading: isResponse ? false : currentAdmin.loading,
i converted it into function provided bools, so each createUserObj can request for the particular version of bool as necessary, so there is less confusion

2021-02-25 20:06 UTC, rawrrencee commented on src/services/axios/index.js
> +    const accessToken = localStorage.getItem('accessToken')
ok

2021-02-25 20:26 UTC, rawrrencee commented on src/services/axios/index.js
> +      message: data.error.message,
i tried to handle this liao, its a bit iffy tho

2021-02-26 02:52 UTC, y1bs approved these changes

2021-02-26 07:14 UTC, natalieloke approved these changes

2021-02-26 07:33 UTC, merged