Cart infrastructure
ianleck/is4103-frontend pull request #60
Opened 2021-03-12 08:26 UTC by y1bs

# Feature
- Cart dropdown
- Cart Page
- Student Upload Profile picture (new use case added to Sys Release 2 list)
- Sensei Upload Profile picture (new use case added to Sys Release 2 list)
- Topbar avatar reflects profile picture/ default avatars

# Changelog:
- Added new avatar photos to public/resources/images/avatars (apprentice, dojo, master and ninjutsu)
- New Cart Components (Page components and Dropdown component)
- New Cart Page
- Edited /src/components/UserActionGroup/UserMenu

# Merge/Review Order

These other PRs should be merged or reviewed first

This PR blocks these other PRs

## Checklist:

- [ ] Merged latest develop
- [ ] PR title makes sense

## Screenshots (where relevant):
### Cart Dropdown
![image](https://user-images.githubusercontent.com/39340177/110912486-f7063900-834e-11eb-8ea2-c8e9dad283c9.png)

### Cart Page when empty
![image](https://user-images.githubusercontent.com/39340177/110912544-06858200-834f-11eb-8a2a-920cc09d5bcf.png)

### Cart Page with Items
![image](https://user-images.githubusercontent.com/39340177/110912565-0d13f980-834f-11eb-8868-e04962a26ba6.png)

### Header with default student avatar
![image](https://user-images.githubusercontent.com/39340177/110912669-2cab2200-834f-11eb-92a4-66e59bdf9b4f.png)

### Header with default sensei avatar
![image](https://user-images.githubusercontent.com/39340177/110912841-5e23ed80-834f-11eb-8889-904f83e53ab7.png)

### Personal Info Card with new upload dp button
![image](https://user-images.githubusercontent.com/39340177/110912912-76940800-834f-11eb-9fec-257f7a76dcdb.png)

### Profile image upload Modal
![image](https://user-images.githubusercontent.com/39340177/110913050-9e836b80-834f-11eb-8795-18ee1842a959.png)

2021-03-12 08:35 UTC, y1bs commented
Hey yall! Let me know if yall have any suggestion or recommendations! Thanks!

2021-03-12 09:47 UTC, rawrrencee commented on src/components/UserActionGroup/index.js
> +  const checkIfShowCart = user.userType !== 'ADMIN' && user.userType !== 'SENSEI'
rmb to change this to use USER_TYPE_ENUM

2021-03-12 09:48 UTC, rawrrencee commented on src/pages/cart/index.js
> +        <div className="col-xl-7 col-lg-12 font-size-18">
convention would be to use col-12 col-xl-7 (start from smallest settings)

2021-03-12 09:49 UTC, rawrrencee commented on src/components/Cart/CartPageComponent/CheckoutCard.js
> +            src="https://cdn.iconscout.com/icon/free/png-512/paypal-54-675727.png"
best if we can download this png and store on our own folder, so it reduces the reliance on internet links for loading stuff (offline files are best)

2021-03-12 09:50 UTC, rawrrencee commented on src/components/Cart/CartPageComponent/CartItemList.js
> +          <div className="card-body">Item 3</div>
think there should only be a single card-body element, but you can have multiple div className="row" inside. understand this is skeleton only though! so for future maybe can modify

2021-03-12 09:51 UTC, rawrrencee commented on src/components/Cart/CartPageComponent/CartItemList.js
> +            </div>
if there is row, then must follow up with col in any div inside, if not the behaviour might not be expected

2021-03-12 09:51 UTC, rawrrencee commented on src/components/Cart/CartPageComponent/CheckoutCard.js
> +      <div className="card-body ">
additional white space behind card-body ahaha

2021-03-12 09:52 UTC, rawrrencee commented on src/pages/cart/index.js
> +        <div className="col-xl-5 col-lg-12 font-size-18">
same as above! i saw some already using the usual convention so this might hv been missed out. hope the catch helps!

2021-03-12 09:53 UTC, rawrrencee requested changes
left some comments for changes based on the typical conventions and some optimisations like downloading pngs to store on our own folder and some code not using ENUM

2021-03-12 10:06 UTC, y1bs commented on src/components/UserActionGroup/index.js
> +  const checkIfShowCart = user.userType !== 'ADMIN' && user.userType !== 'SENSEI'
Ps, missed this out, will change

2021-03-12 10:14 UTC, y1bs commented on src/pages/cart/index.js
> +        <div className="col-xl-7 col-lg-12 font-size-18">
Okies, will change

2021-03-12 10:14 UTC, y1bs commented on src/components/Cart/CartPageComponent/CheckoutCard.js
> +            src="https://cdn.iconscout.com/icon/free/png-512/paypal-54-675727.png"
Aites ok, will uploaded new file

2021-03-12 10:21 UTC, y1bs commented on src/components/Cart/CartPageComponent/CartItemList.js
> +            </div>
Okies, will add a col-12 to the className of line 35

2021-03-12 10:21 UTC, y1bs commented on src/components/Cart/CartPageComponent/CartItemList.js
> +          <div className="card-body">Item 3</div>
Yeps, this one will change again when i implement with backend

2021-03-12 10:23 UTC, y1bs commented on src/components/Cart/CartPageComponent/CheckoutCard.js
> +      <div className="card-body ">
Ps, missed that, will change

2021-03-12 10:24 UTC, y1bs commented on src/pages/cart/index.js
> +        <div className="col-xl-5 col-lg-12 font-size-18">
Yeps, thanks! I changed it le

2021-03-12 10:33 UTC, rawrrencee submitted a review, later dismissed
woohoo! looks very good!

2021-03-13 01:44 UTC, natalieloke reviewed
some minor styling clarifications, can either be fixed in this same PR or in a later PR. other than that everything else looks good 👍

2021-03-13 01:44 UTC, natalieloke commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
this would be equivalent to just if userType === STUDENT right

2021-03-13 01:44 UTC, natalieloke commented on src/components/Profile/PersonalInformationCard/index.js
> +                      {' '}
is this extra space needed?

2021-03-13 01:44 UTC, natalieloke commented on src/components/Profile/PersonalInformationCard/index.js
> +              {user.profileImgUrl ? (
does the linter remove the extra !! if you put it as `!!user.profileImgUrl ? ...` If not i think it is safer to add in !!user.profileImgUrl to catch for falsey values

2021-03-13 01:44 UTC, natalieloke commented on src/components/Cart/CartDropdown/index.js
> +            </Button>
all buttons with `ghost` property? it's one of the styling consistency frameworks  by @rawrrencee, pls advise if it's also applicable for the cart stuff 🙏

2021-03-13 01:44 UTC, natalieloke commented on src/components/Cart/CartDropdown/index.js
> +        </div>
if there are no items, are we standardising to show the `<Empty>` component? 

cc @rawrrencee

2021-03-13 02:28 UTC, y1bs commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
Nopes, its consist of user.userType === STUDENT but it also includes public users where userType is null. I think we still need to show the cart for people who hasn't logged in yet

2021-03-13 02:30 UTC, y1bs commented on src/components/Profile/PersonalInformationCard/index.js
> +                      {' '}
I don't think so? Must have missed this out, thanks for the catch!

2021-03-13 02:50 UTC, y1bs commented on src/components/Profile/PersonalInformationCard/index.js
> +              {user.profileImgUrl ? (
I can't add the !! to the linter, it will cause an error. But I tested it, doesn't seem to have any issues so far. You ok if I leave it as such?

2021-03-13 02:55 UTC, natalieloke commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
I see. Would the flow for public be to click on add to cart -> redirect to register page?

2021-03-13 03:29 UTC, y1bs commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
I think that's a good suggestion! Yall ok with it? Cuz I think this check would be implemented on the buttons of listing pages right? Also, would you add the item to the cart immediately after they login/register or do they have to add it themselves again after successfully logging in?

Initially, I was thinking of implementing redux for the cart and allowing public users to add items to cart without logging in but I would force them to login before checking out. Based on this, the cart will be a standalone redux reducer.
So there could be like 2 flows:
Case 1: cart empty, user not logged in
- If login successful, check user's previous cart and populate Cart with previous Cart items

Case 2: cart has item, user not logged In
- If login successful, user's cart will get populated with data from current Cart

But I think your suggestion of forcing them to login before adding anything to Cart might be a better flow

2021-03-13 06:58 UTC, rawrrencee commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
if redirect to register page upon trying to add to cart, it might be mafan because then the "added item" need to be remembered and added to cart after registering (or we can just make the person manually add again after registering)

I'm more ok with the redux method because usually most stores allow you to add to cart without logging in, but ask u if you wanna checkout as guest or create account during checkout, tho both is fine. @y1bs you can choose!

2021-03-13 07:00 UTC, rawrrencee commented on src/components/Cart/CartDropdown/index.js
> +            </Button>
Oh yeah, can try and see if ghost fits, I prefer to use ghost when you don't want the button to be so obvious but also don't want it to be hidden like "default" is against a white bg. In this case the background is not white, so the button still has visibility. I would say up to you, can try ghost and see if it looks nice beside the Checkout button. 
![image](https://user-images.githubusercontent.com/43084055/111022289-cedd0f80-840c-11eb-875f-c7abc9ac75d1.png)

2021-03-13 07:01 UTC, rawrrencee commented on src/components/Cart/CartDropdown/index.js
> +        </div>
hmm, I think for cart quite unique case. Would you agree if I say we should use text for this? so that users know that the cart is used to store items (instead of just "Empty" which doesn't give enough info - since the cart has no "header", only the icon to indicate that it is a cart)

2021-03-13 07:02 UTC, rawrrencee approved these changes
approved unless further discussion is required, then pls feel free to dismiss and recommit new changes

2021-03-13 07:08 UTC, y1bs commented on src/components/UserActionGroup/index.js
> +    user.userType !== USER_TYPE_ENUM.ADMIN && user.userType !== USER_TYPE_ENUM.SENSEI
Okies, I think we can discuss this again tmr during our meeting? In the meantime, I will also check with Ian

2021-03-13 07:19 UTC, y1bs commented on src/components/Cart/CartDropdown/index.js
> +            </Button>
![image](https://user-images.githubusercontent.com/39340177/111022706-66dbf880-840f-11eb-99fb-9fed111744c4.png)

Just tried, I think we can't use ghost here, wouldn't be able to see the button. Or if yall prefer, i can choose a darker grey for the bg?

2021-03-13 07:32 UTC, rawrrencee commented on src/components/Cart/CartDropdown/index.js
> +            </Button>
hohoho! no need. yup, forgot that ghost is not suitable for non-white bg coz its bg is transparent! i think can leave it as default btn :)

2021-03-13 16:09 UTC, merged